name: Daily

on:
  pull_request:
    branches:
      # any PR to a release branch.
      - '[0-9].[0-9]'
      - 'ror-[0-9].[0-9].[0-9]'
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      use_repo:
        description: 'repo owner and name'
        default: 'ctripcorp/Redis-On-Rocks'
      use_git_ref:
        description: 'git branch or sha to use'
        default: 'xredis_2_ror'

jobs:

  test-ubuntu-jemalloc:
    runs-on: ubuntu-22.04
    if: github.repository == 'ctripcorp/Redis-On-Rocks'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: get rocksdb sha
      id: rocksdb-sha
      run: |
        echo "::set-output name=sha::$(cd deps/rocksdb && git rev-parse HEAD)"
      shell: bash
    - name: cache rocksdb
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: deps/rocksdb
        key: ${{ runner.os }}-rocksdb-${{ steps.rocksdb-sha.outputs.sha }}
    - name: make
      run: |
        sudo apt-get update
        sudo apt-get -y install libsnappy-dev zlib1g-dev libstdc++6
        make REDIS_CFLAGS='-Werror -DREDIS_TEST' -j8
    - name: test
      run: |
        sudo apt-get install tcl8.6
        ./runtest --accurate --verbose --dump-logs
    - name: unittest
      run: ./src/redis-server test all

  test-ubuntu-libc-malloc:
    runs-on: ubuntu-22.04
    if: github.repository == 'ctripcorp/Redis-On-Rocks'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: get rocksdb sha
      id: rocksdb-sha
      run: |
        echo "::set-output name=sha::$(cd deps/rocksdb && git rev-parse HEAD)"
      shell: bash
    - name: cache rocksdb
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: deps/rocksdb
        key: ${{ runner.os }}-rocksdb-${{ steps.rocksdb-sha.outputs.sha }}
    - name: make
      run: |
        sudo apt-get update
        sudo apt-get -y install libsnappy-dev zlib1g-dev libstdc++6
        make MALLOC=libc -j8
    - name: test
      run: |
        sudo apt-get install tcl8.6
        ./runtest --accurate --verbose --dump-logs

  test-sanitizer-address:
    runs-on: ubuntu-22.04
    if: github.repository == 'ctripcorp/Redis-On-Rocks'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: get rocksdb sha
      id: rocksdb-sha
      run: |
        echo "::set-output name=sha::$(cd deps/rocksdb && git rev-parse HEAD)"
      shell: bash
    - name: cache rocksdb
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: deps/rocksdb
        key: ${{ runner.os }}-rocksdb-${{ steps.rocksdb-sha.outputs.sha }}
    - name: make
      run: |
        sudo apt-get update
        sudo apt-get -y install libsnappy-dev zlib1g-dev libstdc++6
        make SANITIZER=address REDIS_CFLAGS='-DREDIS_TEST' -j8
    - name: test
      run: |
        sudo apt-get install tcl8.6 tclx -y
        ./runtest ---tags -nosanitizer -accurate --verbose --dump-logs
    - name: unittest
      run: ./src/redis-server test all

  test-sanitizer-undefined:
    runs-on: ubuntu-22.04
    if: github.repository == 'ctripcorp/Redis-On-Rocks'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: get rocksdb sha
      id: rocksdb-sha
      run: |
        echo "::set-output name=sha::$(cd deps/rocksdb && git rev-parse HEAD)"
      shell: bash
    - name: cache rocksdb
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: deps/rocksdb
        key: ${{ runner.os }}-rocksdb-${{ steps.rocksdb-sha.outputs.sha }}
    - name: make
      run: |
        sudo apt-get update
        sudo apt-get -y install libsnappy-dev zlib1g-dev libstdc++6
        make SANITIZER=undefined REDIS_CFLAGS='-DREDIS_TEST' -j8
    - name: test
      run: |
        sudo apt-get install tcl8.6 tclx -y
        ./runtest --tags -nosanitizer --accurate --verbose --dump-logs
    - name: unittest
      run: ./src/redis-server test all

